### ISSUE TITLE
我有个问题，怎么样才能myfleetgirls 和岛风go 一起用啊？

### ISSUE THREAD

**Issue by OniityanH** [aflyhorse/MFGwrapper#10]
rt

**Comment by Explorare** [comment]
设定 MFGW 的上行端口为 岛风go 的监听端口即可。

**Comment by OniityanH** [comment]
我试过，但是一直显示这个
scala.runtime.NonLocalReturnControl$mcV$sp

我就改了下面这里，是不是改的不对？
upstream_proxy {
     host: 127.0.0.1
     port: 8099
}

**Comment by OniityanH** [comment]
而且只显示这一行，是不是岛风go跟其他的不太一样？

一月 29, 2016 4:59:38 下午 com.twitter.finagle.Init$$anonfun$1 apply$mcV$sp
信息: Finagle version 6.30.0 (rev=745578b931893c432e51da623287144e548cc489) built at 20151015-163818
scala.runtime.NonLocalReturnControl$mcV$sp
scala.runtime.NonLocalReturnControl$mcV$sp
scala.runtime.NonLocalReturnControl$mcV$sp
scala.runtime.NonLocalReturnControl$mcV$sp
scala.runtime.NonLocalReturnControl$mcV$sp
scala.runtime.NonLocalReturnControl$mcV$sp
scala.runtime.NonLocalReturnControl$mcV$sp
scala.runtime.NonLocalReturnControl$mcV$sp
scala.runtime.NonLocalReturnControl$mcV$sp
scala.runtime.NonLocalReturnControl$mcV$sp
scala.runtime.NonLocalReturnControl$mcV$sp
scala.runtime.NonLocalReturnControl$mcV$sp

**Comment by aflyhorse** [comment]
这个代表Wrapper内建的PAC没有启用，非舰娘的请求也传到MFG里去了
如果你是故意使用8080端口的话，刷这个提示是正常现象，白屏的话要另找原因

**Comment by aflyhorse** [comment]
Close this issue due to inactivity. Please reopen it if you have further questions.
