### ISSUE TITLE
连接无法被 Proxifier 抓取到

### ISSUE THREAD

**Issue by Explorare** [aflyhorse/MFGwrapper#11]
我在 Proxifier 中设定抓取 java.exe 的流量到 ShadowSocks，因为 SS 自带的 Privoxy 有 ERROR 500 的 bug，会导致随机猫，所以用 Proxifier 替代之。但是 Proxifier 采取的是主动抓取并抓发流量，而非开监听端口的方式，所以我设定抓取 java.exe 这个进程，在 v0.2 6466a8e 可正常抓取识别，但是在 v0.8.3 745e31c 就不行了。

**Comment by aflyhorse** [comment]
讲真，Java相关的东西我啥都没改
MFG只肯走http代理，倒是我的代码部分可以走socks5……
