### ISSUE TITLE
poi更新了4.0.0之后貌似又暂时用不了了

### ISSUE THREAD

**Issue by fifth** [aflyhorse/MFGwrapper#4]
socks5直连是可以的，http走18080好像没有反应，不知道是不是poi新版本中加入的http代理账号密码的feature的缘故。
待考察

**Comment by fifth** [comment]
不过目测不是你的工具的锅=。=

**Comment by fifth** [comment]
初步判断好像是最早的情况，直接走不了http代理了，因为我换了旧版本发现也不行了
顺便绕一步久了现在sock5直连瞬间感觉流畅了好多

**Comment by aflyhorse** [comment]
走不了http代理了=what，直接走ss的http代理也不行吗
绕一步只会增加约15ms/op的延迟，在第一次打开的时候较明显（有一大堆dmm的图片资源），舰娘部分应当不会有体感影响
