### ISSUE TITLE
开机自动启动失效

### ISSUE THREAD

**Issue by Explorare** [aflyhorse/MFGwrapper#6]
开机自动启动的 Checkbox 有时会自动取消勾选，导致下次开机没有自动启动。望及时修复。
另外请设置开机启动自动运行 MFG，并添加延迟运行选项，因为 SS 开机启动可能会延迟一分钟，导致 MFG 连接出错。添加开机启动自动最小化选项，不然每次都得去点一下很麻烦。

**Comment by aflyhorse** [comment]
延迟运行将在setting内实装。

**Comment by Explorare** [comment]
敲碗坐等。另外这玩意会客观的增加猫的几率啊。另外点关闭的时候自动缩小到任务栏而不是退出。

**Comment by aflyhorse** [comment]
感觉确实会增加猫的几率，不过Privoxy自己500谁都防不住
另今天岛风go简直吃x，我打1-3连猫三次

**Comment by Explorare** [comment]
我目前的方案是 KCV --> MFGW --> Proxifier --> SS，有效避免 Error 500.
