### ISSUE TITLE
[Fiddler] ReadResponse() failed

### ISSUE THREAD

**Issue by Explorare** [aflyhorse/MFGwrapper#8]
```
[Fiddler] ReadResponse() failed: The server did not return a complete response for this request. Server returned 0 bytes. 
```

问题再现方式：
使用 Proxifier 指定 MGFW 的目标代理为 ShadowSocks，然后指定 KCV 的目标代理为 MFGW，就会出现此问题。如果让 MFGW 直接连接 ShadowSocks，会使用 SS 自带的 Privoxy 进行 HTTP/SOCKS 转换，导致 Error 500 经常出现。

**Comment by Mrfuture1** [comment]
请问怎么解决呢？

**Comment by Explorare** [comment]
@Mrfuture1解决办法详见 #7
